name: Fetch Cloudflare Stats

on:
  schedule:
    - cron: '0 16,23 * * *'
  workflow_dispatch:

jobs:
  fetch-stats:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 查看文件结构
        run: |
          ls -R  # 显示仓库所有文件，用于调试
      
      - name: 配置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib
      
      - name: 获取 Cloudflare 统计信息
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python src/fetch_cloudflare_stats.py
      
      - name: 提交并推送更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add history/
          git commit -m "Update statistics" || echo "No changes to commit"
          git push || echo "No changes to push"  
