name: 获取 Cloudflare 统计数据

on:
  schedule:
    # 每天下午4点和晚上11点（UTC时间）运行
    - cron: '0 16,23 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-stats:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 配置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib
      
      - name: 获取 Cloudflare 统计信息
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python src/fetch_cloudflare_stats.py  
